apiVersion: v1
kind: Secret
metadata:
  name: livekit-agents-secrets
type: Opaque
stringData:
  LIVEKIT_URL: wss://livekit.azure.stunner.cc # match your domain
  LIVEKIT_API_KEY: access_token # match your api key
  LIVEKIT_API_SECRET: secret # match your secret
  AZURE_SPEECH_KEY: <your speech key> # terraform output -raw speech_key
  AZURE_SPEECH_REGION: swedencentral # match your Azure Region
  AZURE_OPENAI_ENDPOINT: https://swedencentral.api.cognitive.microsoft.com/openai/deployments/livekit-agent-azure-openai-model/chat/completions?api-version=2024-08-01-preview # terraform output -raw openai_endpoint check Azure AI Foundry at ai.azure.com for the your version
  AZURE_OPENAI_API_KEY: <your azure openai key> #terraform output -raw openapi_key
  OPENAI_API_VERSION: 2024-08-01-preview # check Azure AI Foundry at ai.azure.com for the your version 